### PR TITLE
readme: add logo

### PR DESCRIPTION
**Pull request by g-k**
per @jvehent logo is licensed for public use

### CODE REVIEW

**Comment by ajvb** [comment]
lol...

**Comment by g-k** [comment]
Not sure why this isn't showing up in the preview, but maybe it'll work once landed?

**Comment by hwine** [comment]
The URL doesn't refer to a branch, so it's looking on the default branch. The png won't be there until after it's merged.

_[aside: it'll be interesting to see if this "works right" with my next docs update -- I'm pulling the top level README.md into the docs. that should work since we're hosting on github.io]_

**Comment by hwine** [comment]
oops, my bad - you _also_ can't use a relative URL there i.e. still not showing after merge.

**Pull request merged**
